using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using DebtManager.Domain.Events;
using DebtManager.Domain.Projections;
using DebtManager.Domain.ValueObjects;

namespace DebtManager.Domain.Quality;

/// <summary>
/// Deterministic rule engine for data quality checks.
/// Pure functions: same events always produce the same issues.
/// </summary>
public static class DataQualityRules
{
    public const string RuleSetVersion = "1.0.0";

    public static List<DataQualityIssue> RunAll(
        IReadOnlyList<EventEnvelope> allEnvelopes,
        CashLedgerState cashState,
        BankImportState bankState,
        RecurringState recurringState,
        BudgetState budgetState,
        CategoryState categoryState,
        AssetsState assetsState,
        PortfolioState portfolioState,
        TaxState taxState,
        GoalsState goalsState,
        SetupState setupState,
        DateOnly asOfDate)
    {
        var issues = new List<DataQualityIssue>();
        var now = DateTimeOffset.UtcNow;

        // Cash rules
        CheckCashOrphanEntries(cashState, allEnvelopes, issues, now);
        CheckNegativeBalanceAnomaly(cashState, issues, now);

        // Bank import rules
        CheckBankDecisionConflict(bankState, issues, now);
        CheckBankBatchUndoStuck(bankState, allEnvelopes, issues, now);

        // Recurring rules
        CheckRecurringDuplicatePostings(recurringState, issues, now);
        CheckRecurringArchivedReferences(recurringState, cashState, categoryState, issues, now);

        // Budget rules
        CheckBudgetArchivedCategoryRef(budgetState, categoryState, issues, now);

        // Asset rules
        CheckAssetMissingPrice(assetsState, asOfDate, issues, now);

        // Investment rules
        CheckInvestmentSellExceedsHoldings(portfolioState, issues, now);

        // Tax rules
        CheckTaxUnclassifiedItems(taxState, issues, now);

        // Goal rules
        CheckGoalNegativeContributions(goalsState, issues, now);

        // Setup rules
        CheckSetupIncomplete(setupState, cashState, recurringState, issues, now);

        return issues;
    }

    private static void CheckCashOrphanEntries(
        CashLedgerState cashState,
        IReadOnlyList<EventEnvelope> allEnvelopes,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        // Auto-created accounts (by projector) have CreatedDate == DateOnly.MinValue.
        // These indicate an expense/income event referenced an account that was never
        // formally created via AccountCreated.
        var orphanAccounts = cashState.Accounts.Values
            .Where(a => a.CreatedDate == DateOnly.MinValue)
            .ToList();

        foreach (var acct in orphanAccounts)
        {
            var relatedRows = cashState.Rows.Where(r => r.AccountId == acct.AccountId).ToList();
            issues.Add(new DataQualityIssue
            {
                IssueId = DeterministicId("DQ-CASH-002", acct.AccountId.ToString()),
                Code = "DQ-CASH-002",
                Title = "Orphan cash entry",
                Description = $"Cash entries reference account {acct.AccountId} which was never formally created (auto-generated by projector).",
                Severity = DataQualitySeverity.Error,
                Area = DataQualityArea.Cash,
                DetectedAt = now,
                EffectiveDateFrom = relatedRows.FirstOrDefault()?.EffectiveDate,
                EffectiveDateTo = relatedRows.LastOrDefault()?.EffectiveDate,
                ImpactedEntityIds = new Dictionary<string, string[]>
                {
                    ["AccountId"] = [acct.AccountId.ToString()]
                },
                EvidenceJson = JsonSerializer.Serialize(new { acct.AccountId, acct.Name, rowCount = relatedRows.Count }),
                SuggestedFixes =
                [
                    new DataQualityFixProposal
                    {
                        FixKind = "CreateMissingAccount",
                        Title = "Create missing account",
                        Description = "Create the missing account to restore referential integrity.",
                        RequiresUserInput = true,
                        InputSchemaJson = "{\"accountName\":\"string\",\"accountType\":\"string\"}"
                    }
                ]
            });
        }
    }

    private static void CheckNegativeBalanceAnomaly(
        CashLedgerState cashState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (accountId, account) in cashState.Accounts)
        {
            if (account.Balance < 0 && !account.IsArchived)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-CASH-003", accountId.ToString()),
                    Code = "DQ-CASH-003",
                    Title = "Negative balance anomaly",
                    Description = $"Account '{account.Name}' has a negative balance of {account.Balance:N2} {account.CurrencyCode}.",
                    Severity = DataQualitySeverity.Warning,
                    Area = DataQualityArea.Cash,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["AccountId"] = [accountId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { account.Name, account.Balance, account.CurrencyCode })
                });
            }
        }
    }

    private static void CheckBankDecisionConflict(
        BankImportState bankState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        // Check for conflicts using legacy collections: an imported transaction
        // should not appear in more than one of AppliedLinks, MatchedLinks, IgnoredIds simultaneously.
        var allImportedIds = new HashSet<Guid>();
        foreach (var id in bankState.AppliedLinks.Keys) allImportedIds.Add(id);
        foreach (var id in bankState.MatchedLinks.Keys) allImportedIds.Add(id);
        foreach (var id in bankState.IgnoredIds) allImportedIds.Add(id);

        foreach (var importedId in allImportedIds)
        {
            var hasApplied = bankState.AppliedLinks.ContainsKey(importedId);
            var hasMatched = bankState.MatchedLinks.ContainsKey(importedId);
            var isIgnored = bankState.IgnoredIds.Contains(importedId);

            var activeCount = (hasApplied ? 1 : 0) + (hasMatched ? 1 : 0) + (isIgnored ? 1 : 0);

            if (activeCount > 1)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-BANK-002", importedId.ToString()),
                    Code = "DQ-BANK-002",
                    Title = "Bank import decision conflict",
                    Description = $"Imported transaction {importedId} has multiple active decisions (Applied={hasApplied}, Matched={hasMatched}, Ignored={isIgnored}).",
                    Severity = DataQualitySeverity.Error,
                    Area = DataQualityArea.BankImport,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["ImportedId"] = [importedId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { importedId, hasApplied, hasMatched, isIgnored }),
                    SuggestedFixes =
                    [
                        new DataQualityFixProposal
                        {
                            FixKind = "RevertBankDecision",
                            Title = "Revert decision to Unresolved",
                            Description = "Revert all active decisions for this transaction back to Unresolved state.",
                            RequiresUserInput = false
                        }
                    ]
                });
            }
        }
    }

    private static void CheckBankBatchUndoStuck(
        BankImportState bankState,
        IReadOnlyList<EventEnvelope> allEnvelopes,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        var undoRequested = new HashSet<Guid>();
        var undoCompleted = new HashSet<Guid>();

        foreach (var env in allEnvelopes)
        {
            if (env.EventType == nameof(BankImportBatchUndoRequested))
            {
                var ev = JsonSerializer.Deserialize<BankImportBatchUndoRequested>(env.PayloadJson, DomainJson.Options);
                if (ev != null) undoRequested.Add(ev.BatchId);
            }
            else if (env.EventType == nameof(BankImportBatchUndoCompleted))
            {
                var ev = JsonSerializer.Deserialize<BankImportBatchUndoCompleted>(env.PayloadJson, DomainJson.Options);
                if (ev != null) undoCompleted.Add(ev.BatchId);
            }
        }

        foreach (var batchId in undoRequested.Except(undoCompleted))
        {
            issues.Add(new DataQualityIssue
            {
                IssueId = DeterministicId("DQ-BANK-003", batchId.ToString()),
                Code = "DQ-BANK-003",
                Title = "Batch undo incomplete",
                Description = $"Batch {batchId} has an undo requested but not completed.",
                Severity = DataQualitySeverity.Warning,
                Area = DataQualityArea.BankImport,
                DetectedAt = now,
                ImpactedEntityIds = new Dictionary<string, string[]>
                {
                    ["BatchId"] = [batchId.ToString()]
                },
                EvidenceJson = JsonSerializer.Serialize(new { batchId })
            });
        }
    }

    private static void CheckRecurringDuplicatePostings(
        RecurringState recurringState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (recurringId, item) in recurringState.Items)
        {
            var duplicates = item.PostedDates
                .GroupBy(d => d)
                .Where(g => g.Count() > 1)
                .Select(g => g.Key)
                .ToList();

            foreach (var dupDate in duplicates)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-REC-001", $"{recurringId}|{dupDate:yyyy-MM-dd}"),
                    Code = "DQ-REC-001",
                    Title = "Duplicate recurring posting",
                    Description = $"Recurring template '{item.Reference ?? recurringId.ToString()}' was posted multiple times for cycle {dupDate:yyyy-MM-dd}.",
                    Severity = DataQualitySeverity.Error,
                    Area = DataQualityArea.Recurring,
                    DetectedAt = now,
                    EffectiveDateFrom = dupDate,
                    EffectiveDateTo = dupDate,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["RecurringId"] = [recurringId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { recurringId, dupDate = dupDate.ToString("yyyy-MM-dd"), count = item.PostedDates.Count(d => d == dupDate) })
                });
            }
        }
    }

    private static void CheckRecurringArchivedReferences(
        RecurringState recurringState,
        CashLedgerState cashState,
        CategoryState categoryState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (recurringId, item) in recurringState.Items)
        {
            if (item.IsArchived) continue;

            if (cashState.Accounts.TryGetValue(item.AccountId, out var acct) && acct.IsArchived)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-REC-002", $"{recurringId}|account"),
                    Code = "DQ-REC-002",
                    Title = "Recurring references archived account",
                    Description = $"Active recurring template '{item.Reference ?? recurringId.ToString()}' references archived account '{acct.Name}'.",
                    Severity = DataQualitySeverity.Warning,
                    Area = DataQualityArea.Recurring,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["RecurringId"] = [recurringId.ToString()],
                        ["AccountId"] = [item.AccountId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { recurringId, item.AccountId, accountName = acct.Name }),
                    SuggestedFixes =
                    [
                        new DataQualityFixProposal
                        {
                            FixKind = "ArchiveRecurring",
                            Title = "Archive recurring template",
                            Description = "Archive the recurring template since its account is no longer active.",
                            RequiresUserInput = false
                        }
                    ]
                });
            }

            if (item.CategoryId.HasValue &&
                categoryState.Categories.TryGetValue(item.CategoryId.Value, out var cat) && cat.IsArchived)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-REC-002", $"{recurringId}|category"),
                    Code = "DQ-REC-002",
                    Title = "Recurring references archived category",
                    Description = $"Active recurring template '{item.Reference ?? recurringId.ToString()}' references archived category '{cat.Name}'.",
                    Severity = DataQualitySeverity.Warning,
                    Area = DataQualityArea.Recurring,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["RecurringId"] = [recurringId.ToString()],
                        ["CategoryId"] = [item.CategoryId.Value.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { recurringId, item.CategoryId, categoryName = cat.Name }),
                    SuggestedFixes =
                    [
                        new DataQualityFixProposal
                        {
                            FixKind = "ArchiveRecurring",
                            Title = "Archive recurring template",
                            Description = "Archive the recurring template since its category is no longer active.",
                            RequiresUserInput = false
                        }
                    ]
                });
            }
        }
    }

    private static void CheckBudgetArchivedCategoryRef(
        BudgetState budgetState,
        CategoryState categoryState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (budgetId, budget) in budgetState.Budgets)
        {
            if (budget.IsArchived || !budget.CategoryId.HasValue) continue;

            var catExists = categoryState.Categories.TryGetValue(budget.CategoryId.Value, out var cat);
            if (!catExists || cat!.IsArchived)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-BUD-001", budgetId.ToString()),
                    Code = "DQ-BUD-001",
                    Title = "Budget references missing/archived category",
                    Description = catExists
                        ? $"Budget references archived category '{cat!.Name}'."
                        : $"Budget references non-existent category {budget.CategoryId.Value}.",
                    Severity = DataQualitySeverity.Warning,
                    Area = DataQualityArea.Budgets,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["BudgetId"] = [budgetId.ToString()],
                        ["CategoryId"] = [budget.CategoryId.Value.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { budgetId, budget.CategoryId })
                });
            }
        }
    }

    private static void CheckAssetMissingPrice(
        AssetsState assetsState,
        DateOnly asOfDate,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (assetId, asset) in assetsState.Assets)
        {
            if (asset.IsArchived || asset.Quantity <= 0) continue;

            var hasPrice = assetsState.Prices.Any(p => p.AssetId == assetId && p.AsOfDate <= asOfDate);
            if (!hasPrice)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-ASSET-001", assetId.ToString()),
                    Code = "DQ-ASSET-001",
                    Title = "Asset missing price data",
                    Description = $"Asset '{asset.Name}' has quantity {asset.Quantity} but no price recorded as of {asOfDate:yyyy-MM-dd}.",
                    Severity = DataQualitySeverity.Info,
                    Area = DataQualityArea.Assets,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["AssetId"] = [assetId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { assetId, asset.Name, asset.Quantity, asOfDate = asOfDate.ToString("yyyy-MM-dd") })
                });
            }
        }
    }

    private static void CheckInvestmentSellExceedsHoldings(
        PortfolioState portfolioState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (key, position) in portfolioState.Positions)
        {
            if (position.Quantity < 0)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-INV-001", $"{key.AccountId}|{key.AssetId}"),
                    Code = "DQ-INV-001",
                    Title = "Sell exceeds holdings",
                    Description = $"Position in '{position.Symbol}' has negative quantity ({position.Quantity:N4}) — sell exceeded holdings.",
                    Severity = DataQualitySeverity.Critical,
                    Area = DataQualityArea.Investments,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["AccountId"] = [key.AccountId.ToString()],
                        ["AssetId"] = [key.AssetId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { key.AccountId, key.AssetId, position.Symbol, position.Quantity })
                });
            }
        }
    }

    private static void CheckTaxUnclassifiedItems(
        TaxState taxState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        if (taxState.Profiles.Count == 0) return;

        var totalClassifications = taxState.ConfirmedClassifications.Count;
        var unclassifiedCount = taxState.ConfirmedClassifications
            .Count(c => string.IsNullOrWhiteSpace(c.Value) || c.Value == "Unclassified");

        if (unclassifiedCount > 0 && totalClassifications > 0)
        {
            var pct = (decimal)unclassifiedCount / totalClassifications * 100m;
            if (pct >= 10m)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-TAX-001", $"unclassified-{unclassifiedCount}"),
                    Code = "DQ-TAX-001",
                    Title = "Tax items unclassified",
                    Description = $"{unclassifiedCount} of {totalClassifications} tax classifications are unclassified ({pct:N0}%).",
                    Severity = DataQualitySeverity.Warning,
                    Area = DataQualityArea.Taxes,
                    DetectedAt = now,
                    EvidenceJson = JsonSerializer.Serialize(new { unclassifiedCount, totalClassifications, percentUnclassified = pct }),
                    SuggestedFixes =
                    [
                        new DataQualityFixProposal
                        {
                            FixKind = "NavigateToTaxes",
                            Title = "Open Taxes page",
                            Description = "Review and confirm tax classifications for unclassified items.",
                            RequiresUserInput = true
                        }
                    ]
                });
            }
        }
    }

    private static void CheckGoalNegativeContributions(
        GoalsState goalsState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        foreach (var (goalId, goal) in goalsState.Goals)
        {
            if (goal.IsArchived) continue;

            var netContributed = goalsState.TotalContributed(goalId);
            if (netContributed < 0)
            {
                issues.Add(new DataQualityIssue
                {
                    IssueId = DeterministicId("DQ-GOAL-001", goalId.ToString()),
                    Code = "DQ-GOAL-001",
                    Title = "Goal has net negative contributions",
                    Description = $"Goal '{goal.Name}' has net contributions of {netContributed:N2} — more reversed than contributed.",
                    Severity = DataQualitySeverity.Error,
                    Area = DataQualityArea.Goals,
                    DetectedAt = now,
                    ImpactedEntityIds = new Dictionary<string, string[]>
                    {
                        ["GoalId"] = [goalId.ToString()]
                    },
                    EvidenceJson = JsonSerializer.Serialize(new { goalId, goal.Name, netContributed })
                });
            }
        }
    }

    private static void CheckSetupIncomplete(
        SetupState setupState,
        CashLedgerState cashState,
        RecurringState recurringState,
        List<DataQualityIssue> issues,
        DateTimeOffset now)
    {
        if (setupState.IsInitialSetupCompleted) return;

        var hasData = cashState.Accounts.Count > 0 || recurringState.Items.Count > 0;
        if (hasData)
        {
            issues.Add(new DataQualityIssue
            {
                IssueId = DeterministicId("DQ-SETUP-001", "incomplete"),
                Code = "DQ-SETUP-001",
                Title = "Setup incomplete with existing data",
                Description = "Initial setup was not completed, but data already exists across modules. Consider completing setup.",
                Severity = DataQualitySeverity.Info,
                Area = DataQualityArea.Setup,
                DetectedAt = now,
                EvidenceJson = JsonSerializer.Serialize(new { accountCount = cashState.Accounts.Count, recurringCount = recurringState.Items.Count })
            });
        }
    }

    /// <summary>
    /// Generate a deterministic GUID from a rule code + entity key to ensure
    /// same events always produce the same IssueId.
    /// </summary>
    public static Guid DeterministicId(string code, string entityKey)
    {
        var input = $"{code}|{entityKey}";
        var bytes = Encoding.UTF8.GetBytes(input);
        var hash = SHA256.HashData(bytes);
        Span<byte> guidBytes = stackalloc byte[16];
        hash.AsSpan(0, 16).CopyTo(guidBytes);
        return new Guid(guidBytes);
    }
}
